# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'GNGeocoder' do
pod 'AFNetworking'
pod 'CWLSynthesizeSingleton'
end

target 'GNGeocoderTests' do
pod 'CWLSynthesizeSingleton'
end

